# Generated by Django 5.1.15 on 2026-03-19 06:56

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state_code', models.CharField(blank=True, max_length=2)),
                ('zipcode', models.CharField(blank=True, db_index=True, max_length=10)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('property_type', models.CharField(blank=True, max_length=50)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('geography', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties_set', to='geography.geography')),
            ],
            options={
                'verbose_name_plural': 'properties',
            },
        ),
        migrations.CreateModel(
            name='MetricData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(db_index=True, max_length=50)),
                ('period', models.DateField(db_index=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('geography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_data', to='geography.geography')),
            ],
            options={
                'indexes': [models.Index(fields=['geography', 'metric', 'period'], name='housing_met_geograp_1cdbc5_idx'), models.Index(fields=['metric', 'period'], name='housing_met_metric_ea6732_idx')],
                'constraints': [models.UniqueConstraint(fields=('geography', 'metric', 'period'), name='unique_geography_metric_period')],
            },
        ),
        migrations.CreateModel(
            name='PropertyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('sale', 'Sale'), ('listing', 'Listing'), ('assessment', 'Assessment')], max_length=30)),
                ('event_date', models.DateField(db_index=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='housing.property')),
            ],
            options={
                'indexes': [models.Index(fields=['property', 'event_type', 'event_date'], name='housing_pro_propert_6f3f88_idx')],
            },
        ),
    ]
