# Generated by Django 5.1.15 on 2026-03-19 06:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_type', models.CharField(choices=[('zipcode', 'Zip Code'), ('county', 'County'), ('city', 'City'), ('metro', 'Metro'), ('state', 'State')], db_index=True, max_length=20)),
                ('geo_id', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('state_code', models.CharField(blank=True, db_index=True, max_length=2)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('properties', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name_plural': 'geographies',
                'indexes': [models.Index(fields=['geo_type', 'geo_id'], name='geography_g_geo_typ_bc8a89_idx'), models.Index(fields=['geo_type', 'state_code'], name='geography_g_geo_typ_a1ed64_idx')],
                'constraints': [models.UniqueConstraint(fields=('geo_type', 'geo_id'), name='unique_geo_type_geo_id')],
            },
        ),
    ]
